version: '3.8'

services:
  registry:
    build:
      context: .
      dockerfile: docker/registry.Dockerfile
    ports:
      - "8080:8080"
    networks:
      rpc_net:
        ipv4_address: 192.168.1.10

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "12000:12000"
    depends_on:
      - registry
    networks:
      rpc_net:
        ipv4_address: 192.168.1.11
    environment:
      - REGISTRY_URL=http://192.168.1.10:8080

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    depends_on:
      - server
      - registry
    networks:
      - rpc_net
    environment:
      - SERVER_URL=http://192.168.1.11:12000
      - REGISTRY_URL=http://192.168.1.10:8080

networks:
  rpc_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
